name: Quick Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'basic'
        type: choice
        options:
        - basic
        - full
        - integration

jobs:
  quick-test:
    name: Quick Application Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test environment
      run: |
        python -c "
        with open('.env', 'w') as f:
            f.write('OPENWEATHER_API_KEY=test_key\n')
        "
        python -c "import os; os.makedirs('data', exist_ok=True)"
        
    - name: Run basic tests
      if: github.event.inputs.test_type == 'basic'
      run: |
        python -c "
        import sys
        import os
        sys.path.insert(0, os.getcwd())
        
        try:
            from src.models.weather_models import CurrentWeather
            print('✅ Models import successful')
            
            from src.utils.validators import validate_api_key
            print('✅ Validators import successful')
            
            from src.config.config import config_manager
            print('✅ Config import successful')
            
            print('🎉 Basic tests passed!')
        except Exception as e:
            print(f'❌ Test failed: {e}')
            sys.exit(1)
        "
        
    - name: Run full tests
      if: github.event.inputs.test_type == 'full'
      run: |
        pip install pytest
        pytest tests/ -v
        
    - name: Run integration tests
      if: github.event.inputs.test_type == 'integration'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run -a python -c "
        import sys
        import os
        sys.path.insert(0, os.getcwd())
        
        try:
            import tkinter as tk
            root = tk.Tk()
            root.withdraw()
            root.destroy()
            print('✅ TKinter test passed')
            
            from src.app_gui import WeatherDashboardGUIApp
            print('✅ GUI app import successful')
            
            print('🎉 Integration tests passed!')
        except Exception as e:
            print(f'❌ Integration test failed: {e}')
            sys.exit(1)
        "
